routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('crm_statuses', 'Admin\CrmStatusesController');
    Route::post('crm_statuses_mass_destroy', ['uses' => 'Admin\CrmStatusesController@massDestroy', 'as' => 'crm_statuses.mass_destroy']);
    Route::resource('crm_customers', 'Admin\CrmCustomersController');
    Route::post('crm_customers_mass_destroy', ['uses' => 'Admin\CrmCustomersController@massDestroy', 'as' => 'crm_customers.mass_destroy']);
    Route::resource('crm_notes', 'Admin\CrmNotesController');
    Route::post('crm_notes_mass_destroy', ['uses' => 'Admin\CrmNotesController@massDestroy', 'as' => 'crm_notes.mass_destroy']);
    Route::resource('crm_documents', 'Admin\CrmDocumentsController');
    Route::post('crm_documents_mass_destroy', ['uses' => 'Admin\CrmDocumentsController@massDestroy', 'as' => 'crm_documents.mass_destroy']);
    Route::resource('inbounds', 'Admin\InboundsController');
    Route::post('inbounds_mass_destroy', ['uses' => 'Admin\InboundsController@massDestroy', 'as' => 'inbounds.mass_destroy']);
    Route::post('inbounds_restore/{id}', ['uses' => 'Admin\InboundsController@restore', 'as' => 'inbounds.restore']);
    Route::delete('inbounds_perma_del/{id}', ['uses' => 'Admin\InboundsController@perma_del', 'as' => 'inbounds.perma_del']);
    Route::resource('bookings', 'Admin\BookingsController');
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingsController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::post('bookings_restore/{id}', ['uses' => 'Admin\BookingsController@restore', 'as' => 'bookings.restore']);
    Route::delete('bookings_perma_del/{id}', ['uses' => 'Admin\BookingsController@perma_del', 'as' => 'bookings.perma_del']);
    Route::get('booking_details','Admin\BookingDetailsController@index');

    Route::resource('booking_details', 'Admin\BookingDetailsController');
    Route::post('booking_details_mass_destroy', ['uses' => 'Admin\BookingDetailsController@massDestroy', 'as' => 'booking_details.mass_destroy']);
    Route::post('booking_details_restore/{id}', ['uses' => 'Admin\BookingDetailsController@restore', 'as' => 'booking_details.restore']);
    Route::delete('booking_details_perma_del/{id}', ['uses' => 'Admin\BookingDetailsController@perma_del', 'as' => 'booking_details.perma_del']);



 
});

app/Http/Controllers/Admin/BookingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Booking;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreBookingsRequest;
use App\Http\Requests\Admin\UpdateBookingsRequest;
use App\Http\Controllers\Traits\FileUploadTrait;
use Yajra\DataTables\DataTables;

class BookingsController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Booking.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('booking_access')) {
            return abort(401);
        }


        
        if (request()->ajax()) {
            $query = Booking::query();
            $template = 'actionsTemplate';
            if(request('show_deleted') == 1) {
                
        if (! Gate::allows('booking_delete')) {
            return abort(401);
        }
                $query->onlyTrashed();
                $template = 'restoreTemplate';
            }
            $query->select([
                'bookings.id',
                'bookings.date',
                'bookings.consignment_no',
                'bookings.consigner_name',
                'bookings.consigner_mobile_no',
                'bookings.from',
                'bookings.to',
                'bookings.consignee_name',
                'bookings.consignee_mobile_no',
                'bookings.service_type',
                'bookings.weight',
                'bookings.dox',
                'bookings.amount',
                'bookings.status',
                'bookings.shipment_status',
                'bookings.pod',
                'bookings.descvd',
            ]);
            $table = Datatables::of($query);

            $table->setRowAttr([
                'data-entry-id' => '{{$id}}',
            ]);
            $table->addColumn('massDelete', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');
            $table->editColumn('actions', function ($row) use ($template) {
                $gateKey  = 'booking_';
                $routeKey = 'admin.bookings';

                return view($template, compact('row', 'gateKey', 'routeKey'));
            });
            $table->editColumn('date', function ($row) {
                return $row->date ? $row->date : '';
            });
            $table->editColumn('consignment_no', function ($row) {
                return $row->consignment_no ? $row->consignment_no : '';
            });
            $table->editColumn('consigner_name', function ($row) {
                return $row->consigner_name ? $row->consigner_name : '';
            });
            $table->editColumn('consigner_mobile_no', function ($row) {
                return $row->consigner_mobile_no ? $row->consigner_mobile_no : '';
            });
            $table->editColumn('from', function ($row) {
                return $row->from ? $row->from : '';
            });
            $table->editColumn('to', function ($row) {
                return $row->to ? $row->to : '';
            });
            $table->editColumn('consignee_name', function ($row) {
                return $row->consignee_name ? $row->consignee_name : '';
            });
            $table->editColumn('consignee_mobile_no', function ($row) {
                return $row->consignee_mobile_no ? $row->consignee_mobile_no : '';
            });
            $table->editColumn('service_type', function ($row) {
                return $row->service_type ? $row->service_type : '';
            });
            $table->editColumn('weight', function ($row) {
                return $row->weight ? $row->weight : '';
            });
            $table->editColumn('dox', function ($row) {
                return $row->dox ? $row->dox : '';
            });
            $table->editColumn('amount', function ($row) {
                return $row->amount ? $row->amount : '';
            });
            $table->editColumn('status', function ($row) {
                return $row->status ? $row->status : '';
            });
            $table->editColumn('shipment_status', function ($row) {
                return $row->shipment_status ? $row->shipment_status : '';
            });
            $table->editColumn('pod', function ($row) {
                if($row->pod) { return '<a href="'.asset(env('UPLOAD_PATH').'/'.$row->pod) .'" target="_blank">Download file</a>'; };
            });
            $table->editColumn('descvd', function ($row) {
                return $row->descvd ? $row->descvd : '';
            });

            $table->rawColumns(['actions','massDelete','pod']);

            return $table->make(true);
        }

        return view('admin.bookings.index');
    }

    /**
     * Show the form for creating new Booking.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('booking_create')) {
            return abort(401);
        }        $enum_service_type = Booking::$enum_service_type;
                    $enum_shipment_status = Booking::$enum_shipment_status;
            
        return view('admin.bookings.create', compact('enum_service_type', 'enum_shipment_status'));
    }

    /**
     * Store a newly created Booking in storage.
     *
     * @param  \App\Http\Requests\StoreBookingsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookingsRequest $request)
    {
        if (! Gate::allows('booking_create')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $booking = Booking::create($request->all());



        return redirect()->route('admin.bookings.index');
    }


    /**
     * Show the form for editing Booking.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('booking_edit')) {
            return abort(401);
        }        $enum_service_type = Booking::$enum_service_type;
                    $enum_shipment_status = Booking::$enum_shipment_status;
            
        $booking = Booking::findOrFail($id);

        return view('admin.bookings.edit', compact('booking', 'enum_service_type', 'enum_shipment_status'));
    }

    /**
     * Update Booking in storage.
     *
     * @param  \App\Http\Requests\UpdateBookingsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookingsRequest $request, $id)
    {
        if (! Gate::allows('booking_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $booking = Booking::findOrFail($id);
        $booking->update($request->all());



        return redirect()->route('admin.bookings.index');
    }


    /**
     * Display Booking.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('booking_view')) {
            return abort(401);
        }
        $booking_details = \App\BookingDetail::where('booking_id', $id)->get();

        $booking = Booking::findOrFail($id);

        return view('admin.bookings.show', compact('booking', 'booking_details'));
    }


    /**
     * Remove Booking from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('booking_delete')) {
            return abort(401);
        }
        $booking = Booking::findOrFail($id);
        $booking->delete();

        return redirect()->route('admin.bookings.index');
    }

    /**
     * Delete all selected Booking at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('booking_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Booking::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Booking from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('booking_delete')) {
            return abort(401);
        }
        $booking = Booking::onlyTrashed()->findOrFail($id);
        $booking->restore();

        return redirect()->route('admin.bookings.index');
    }

    /**
     * Permanently delete Booking from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('booking_delete')) {
            return abort(401);
        }
        $booking = Booking::onlyTrashed()->findOrFail($id);
        $booking->forceDelete();

        return redirect()->route('admin.bookings.index');
    }
}

app/Http/Controllers/Api/V1/BookingsController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Booking;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreBookingsRequest;
use App\Http\Requests\Admin\UpdateBookingsRequest;
use App\Http\Controllers\Traits\FileUploadTrait;
use Yajra\DataTables\DataTables;

class BookingsController extends Controller
{
    use FileUploadTrait;

    public function index()
    {
        return Booking::all();
    }

    public function show($id)
    {
        return Booking::findOrFail($id);
    }

    public function update(UpdateBookingsRequest $request, $id)
    {
        $request = $this->saveFiles($request);
        $booking = Booking::findOrFail($id);
        $booking->update($request->all());
        

        return $booking;
    }

    public function store(StoreBookingsRequest $request)
    {
        $request = $this->saveFiles($request);
        $booking = Booking::create($request->all());
        

        return $booking;
    }

    public function destroy($id)
    {
        $booking = Booking::findOrFail($id);
        $booking->delete();
        return '';
    }
}

app/Http/Livewire/Booking.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class Booking extends Component
{
	 use WithPagination;
	 public $search;
     protected $listeners = ['refreshData','editBooking'];
    public function editBooking($bookingid){
    	$this->emit('mybookingid', $bookingid);
    }
    public function deleteBooking($bookingid){
    	$data = \App\BookingDetail::where('id',$bookingid)->delete();
        if($data)
        {
             session()->flash('success1', 'Booking Detail deleted successfully.');
             $this->emit('alert', ['type' => 'success', 'message' => 'Booking Detail deleted successfully.']);

        }else{
             session()->flash('error1', 'Somethink went wrong.');
             $this->emit('alert', ['type' => 'error', 'message' => 'Somethink went wrong.']);

        }
    	$this->refreshData();
        $this->emit('refreshData');

    }
    public function refreshData(){
    	$this->render();
    }
    public function render()
    {
        return view('livewire.booking',[
        	'booking' => \App\BookingDetail::where('details','like','%'.$this->search.'%')->orWhere('location','like','%'.$this->search.'%')->paginate(10)
    	]);
    }
}

resources/views/admin/bookings/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.booking.title')</h3>
    @can('booking_create')
    <p>
        <a href="{{ route('admin.bookings.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    @can('booking_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.bookings.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.bookings.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped ajaxTable @can('booking_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('booking_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.booking.fields.date')</th>
                        <th>@lang('quickadmin.booking.fields.consignment-no')</th>
                        <th>@lang('quickadmin.booking.fields.consigner-name')</th>
                        <th>@lang('quickadmin.booking.fields.consigner-mobile-no')</th>
                        <th>@lang('quickadmin.booking.fields.from')</th>
                        <th>@lang('quickadmin.booking.fields.to')</th>
                        <th>@lang('quickadmin.booking.fields.consignee-name')</th>
                        <th>@lang('quickadmin.booking.fields.consignee-mobile-no')</th>
                        <th>@lang('quickadmin.booking.fields.service-type')</th>
                        <th>@lang('quickadmin.booking.fields.weight')</th>
                        <th>@lang('quickadmin.booking.fields.dox')</th>
                        <th>@lang('quickadmin.booking.fields.amount')</th>
                        <th>@lang('quickadmin.booking.fields.status')</th>
                        <th>@lang('quickadmin.booking.fields.shipment-status')</th>
                        <th>@lang('quickadmin.booking.fields.pod')</th>
                        <th>@lang('quickadmin.booking.fields.descvd')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('booking_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.bookings.mass_destroy') }}'; @endif
        @endcan
        $(document).ready(function () {
            window.dtDefaultOptions.ajax = '{!! route('admin.bookings.index') !!}?show_deleted={{ request('show_deleted') }}';
            window.dtDefaultOptions.columns = [@can('booking_delete')
                @if ( request('show_deleted') != 1 )
                    {data: 'massDelete', name: 'id', searchable: false, sortable: false},
                @endif
                @endcan{data: 'date', name: 'date'},
                {data: 'consignment_no', name: 'consignment_no'},
                {data: 'consigner_name', name: 'consigner_name'},
                {data: 'consigner_mobile_no', name: 'consigner_mobile_no'},
                {data: 'from', name: 'from'},
                {data: 'to', name: 'to'},
                {data: 'consignee_name', name: 'consignee_name'},
                {data: 'consignee_mobile_no', name: 'consignee_mobile_no'},
                {data: 'service_type', name: 'service_type'},
                {data: 'weight', name: 'weight'},
                {data: 'dox', name: 'dox'},
                {data: 'amount', name: 'amount'},
                {data: 'status', name: 'status'},
                {data: 'shipment_status', name: 'shipment_status'},
                {data: 'pod', name: 'pod'},
                {data: 'descvd', name: 'descvd'},
                
                {data: 'actions', name: 'actions', searchable: false, sortable: false}
            ];
            processAjaxTables();
        });
    </script>
@endsection

resources/views/admin/bookings/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.booking.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.booking.fields.date')</th>
                            <td field-key='date'>{{ $booking->date }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.consignment-no')</th>
                            <td field-key='consignment_no'>{{ $booking->consignment_no }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.consigner-name')</th>
                            <td field-key='consigner_name'>{{ $booking->consigner_name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.consigner-mobile-no')</th>
                            <td field-key='consigner_mobile_no'>{{ $booking->consigner_mobile_no }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.from')</th>
                            <td field-key='from'>{{ $booking->from }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.to')</th>
                            <td field-key='to'>{{ $booking->to }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.consignee-name')</th>
                            <td field-key='consignee_name'>{{ $booking->consignee_name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.consignee-mobile-no')</th>
                            <td field-key='consignee_mobile_no'>{{ $booking->consignee_mobile_no }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.service-type')</th>
                            <td field-key='service_type'>{{ $booking->service_type }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.weight')</th>
                            <td field-key='weight'>{{ $booking->weight }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.dox')</th>
                            <td field-key='dox'>{{ $booking->dox }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.amount')</th>
                            <td field-key='amount'>{{ $booking->amount }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.status')</th>
                            <td field-key='status'>{{ $booking->status }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.shipment-status')</th>
                            <td field-key='shipment_status'>{{ $booking->shipment_status }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.pod')</th>
                            <td field-key='pod'>@if($booking->pod)<a href="{{ asset(env('UPLOAD_PATH').'/' . $booking->pod) }}" target="_blank">Download file</a>@endif</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.booking.fields.descvd')</th>
                            <td field-key='descvd'>{!! $booking->descvd !!}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#booking_details" aria-controls="booking_details" role="tab" data-toggle="tab">Booking details</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="booking_details">
<table class="table table-bordered table-striped {{ count($booking_details) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.booking-details.fields.booking')</th>
                        <th>@lang('quickadmin.booking-details.fields.location')</th>
                        <th>@lang('quickadmin.booking-details.fields.details')</th>
                        <th>@lang('quickadmin.booking-details.fields.date')</th>
                        <th>@lang('quickadmin.booking-details.fields.time')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($booking_details) > 0)
            @foreach ($booking_details as $booking_detail)
                <tr data-entry-id="{{ $booking_detail->id }}">
                    <td field-key='booking'>{{ $booking_detail->booking->consignment_no ?? '' }}</td>
                                <td field-key='location'>{{ $booking_detail->location }}</td>
                                <td field-key='details'>{{ $booking_detail->details }}</td>
                                <td field-key='date'>{{ $booking_detail->date }}</td>
                                <td field-key='time'>{{ $booking_detail->time }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('booking_detail_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.booking_details.restore', $booking_detail->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('booking_detail_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.booking_details.perma_del', $booking_detail->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('booking_detail_view')
                                    <a href="{{ route('admin.booking_details.show',[$booking_detail->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('booking_detail_edit')
                                    <a href="{{ route('admin.booking_details.edit',[$booking_detail->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('booking_detail_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.booking_details.destroy', $booking_detail->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="10">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.bookings.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop

@section('javascript')
    @parent
    <script src="//cdn.ckeditor.com/4.5.4/full/ckeditor.js"></script>
    <script>
        $('.editor').each(function () {
                  CKEDITOR.replace($(this).attr('id'),{
                    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        });
    </script>

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function(){
            moment.updateLocale('{{ App::getLocale() }}', {
                week: { dow: 1 } // Monday is the first day of the week
            });
            
            $('.datetime').datetimepicker({
                format: "{{ config('app.datetime_format_moment') }}",
                locale: "{{ App::getLocale() }}",
                sideBySide: true,
            });
            
        });
    </script>
            
@stop