routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('crm_statuses', 'Admin\CrmStatusesController');
    Route::post('crm_statuses_mass_destroy', ['uses' => 'Admin\CrmStatusesController@massDestroy', 'as' => 'crm_statuses.mass_destroy']);
    Route::resource('crm_customers', 'Admin\CrmCustomersController');
    Route::post('crm_customers_mass_destroy', ['uses' => 'Admin\CrmCustomersController@massDestroy', 'as' => 'crm_customers.mass_destroy']);
    Route::resource('crm_notes', 'Admin\CrmNotesController');
    Route::post('crm_notes_mass_destroy', ['uses' => 'Admin\CrmNotesController@massDestroy', 'as' => 'crm_notes.mass_destroy']);
    Route::resource('crm_documents', 'Admin\CrmDocumentsController');
    Route::post('crm_documents_mass_destroy', ['uses' => 'Admin\CrmDocumentsController@massDestroy', 'as' => 'crm_documents.mass_destroy']);
    Route::resource('inbounds', 'Admin\InboundsController');
    Route::post('inbounds_mass_destroy', ['uses' => 'Admin\InboundsController@massDestroy', 'as' => 'inbounds.mass_destroy']);
    Route::post('inbounds_restore/{id}', ['uses' => 'Admin\InboundsController@restore', 'as' => 'inbounds.restore']);
    Route::delete('inbounds_perma_del/{id}', ['uses' => 'Admin\InboundsController@perma_del', 'as' => 'inbounds.perma_del']);
    Route::resource('bookings', 'Admin\BookingsController');
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingsController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::post('bookings_restore/{id}', ['uses' => 'Admin\BookingsController@restore', 'as' => 'bookings.restore']);
    Route::delete('bookings_perma_del/{id}', ['uses' => 'Admin\BookingsController@perma_del', 'as' => 'bookings.perma_del']);
    Route::get('booking_details','Admin\BookingDetailsController@index');

    Route::resource('booking_details', 'Admin\BookingDetailsController');
    Route::post('booking_details_mass_destroy', ['uses' => 'Admin\BookingDetailsController@massDestroy', 'as' => 'booking_details.mass_destroy']);
    Route::post('booking_details_restore/{id}', ['uses' => 'Admin\BookingDetailsController@restore', 'as' => 'booking_details.restore']);
    Route::delete('booking_details_perma_del/{id}', ['uses' => 'Admin\BookingDetailsController@perma_del', 'as' => 'booking_details.perma_del']);



 
});

app/CrmCustomer.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class CrmCustomer
 *
 * @package App
 * @property string $first_name
 * @property string $last_name
 * @property string $crm_status
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property string $skype
 * @property string $website
 * @property text $description
*/
class CrmCustomer extends Model
{
    protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'address', 'skype', 'website', 'description', 'crm_status_id'];
    protected $hidden = [];
    
    
    public static function boot()
    {
        parent::boot();

        CrmCustomer::observe(new \App\Observers\UserActionsObserver);
    }

    /**
     * Set to null if empty
     * @param $input
     */
    public function setCrmStatusIdAttribute($input)
    {
        $this->attributes['crm_status_id'] = $input ? $input : null;
    }
    
    public function crm_status()
    {
        return $this->belongsTo(CrmStatus::class, 'crm_status_id');
    }
    
}

app/Http/Controllers/Admin/CrmCustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CrmCustomer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCrmCustomersRequest;
use App\Http\Requests\Admin\UpdateCrmCustomersRequest;

class CrmCustomersController extends Controller
{
    /**
     * Display a listing of CrmCustomer.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('crm_customer_access')) {
            return abort(401);
        }


                $crm_customers = CrmCustomer::all();

        return view('admin.crm_customers.index', compact('crm_customers'));
    }

    /**
     * Show the form for creating new CrmCustomer.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('crm_customer_create')) {
            return abort(401);
        }
        
        $crm_statuses = \App\CrmStatus::get()->pluck('title', 'id')->prepend(trans('quickadmin.qa_please_select'), '');

        return view('admin.crm_customers.create', compact('crm_statuses'));
    }

    /**
     * Store a newly created CrmCustomer in storage.
     *
     * @param  \App\Http\Requests\StoreCrmCustomersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCrmCustomersRequest $request)
    {
        if (! Gate::allows('crm_customer_create')) {
            return abort(401);
        }
        $crm_customer = CrmCustomer::create($request->all());



        return redirect()->route('admin.crm_customers.index');
    }


    /**
     * Show the form for editing CrmCustomer.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('crm_customer_edit')) {
            return abort(401);
        }
        
        $crm_statuses = \App\CrmStatus::get()->pluck('title', 'id')->prepend(trans('quickadmin.qa_please_select'), '');

        $crm_customer = CrmCustomer::findOrFail($id);

        return view('admin.crm_customers.edit', compact('crm_customer', 'crm_statuses'));
    }

    /**
     * Update CrmCustomer in storage.
     *
     * @param  \App\Http\Requests\UpdateCrmCustomersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCrmCustomersRequest $request, $id)
    {
        if (! Gate::allows('crm_customer_edit')) {
            return abort(401);
        }
        $crm_customer = CrmCustomer::findOrFail($id);
        $crm_customer->update($request->all());



        return redirect()->route('admin.crm_customers.index');
    }


    /**
     * Display CrmCustomer.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('crm_customer_view')) {
            return abort(401);
        }
        
        $crm_statuses = \App\CrmStatus::get()->pluck('title', 'id')->prepend(trans('quickadmin.qa_please_select'), '');$crm_notes = \App\CrmNote::where('customer_id', $id)->get();$crm_documents = \App\CrmDocument::where('customer_id', $id)->get();

        $crm_customer = CrmCustomer::findOrFail($id);

        return view('admin.crm_customers.show', compact('crm_customer', 'crm_notes', 'crm_documents'));
    }


    /**
     * Remove CrmCustomer from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('crm_customer_delete')) {
            return abort(401);
        }
        $crm_customer = CrmCustomer::findOrFail($id);
        $crm_customer->delete();

        return redirect()->route('admin.crm_customers.index');
    }

    /**
     * Delete all selected CrmCustomer at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('crm_customer_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = CrmCustomer::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/crm_customers/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-customers.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.crm_customers.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('first_name', trans('quickadmin.crm-customers.fields.first-name').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('first_name', old('first_name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('first_name'))
                        <p class="help-block">
                            {{ $errors->first('first_name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('last_name', trans('quickadmin.crm-customers.fields.last-name').'', ['class' => 'control-label']) !!}
                    {!! Form::text('last_name', old('last_name'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('last_name'))
                        <p class="help-block">
                            {{ $errors->first('last_name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('crm_status_id', trans('quickadmin.crm-customers.fields.crm-status').'*', ['class' => 'control-label']) !!}
                    {!! Form::select('crm_status_id', $crm_statuses, old('crm_status_id'), ['class' => 'form-control select2', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('crm_status_id'))
                        <p class="help-block">
                            {{ $errors->first('crm_status_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', trans('quickadmin.crm-customers.fields.email').'', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('phone', trans('quickadmin.crm-customers.fields.phone').'', ['class' => 'control-label']) !!}
                    {!! Form::text('phone', old('phone'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('phone'))
                        <p class="help-block">
                            {{ $errors->first('phone') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('address', trans('quickadmin.crm-customers.fields.address').'', ['class' => 'control-label']) !!}
                    {!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('address'))
                        <p class="help-block">
                            {{ $errors->first('address') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('skype', trans('quickadmin.crm-customers.fields.skype').'', ['class' => 'control-label']) !!}
                    {!! Form::text('skype', old('skype'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('skype'))
                        <p class="help-block">
                            {{ $errors->first('skype') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('website', trans('quickadmin.crm-customers.fields.website').'', ['class' => 'control-label']) !!}
                    {!! Form::text('website', old('website'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('website'))
                        <p class="help-block">
                            {{ $errors->first('website') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('description', trans('quickadmin.crm-customers.fields.description').'', ['class' => 'control-label']) !!}
                    {!! Form::textarea('description', old('description'), ['class' => 'form-control ', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('description'))
                        <p class="help-block">
                            {{ $errors->first('description') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/crm_customers/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-customers.title')</h3>
    @can('crm_customer_create')
    <p>
        <a href="{{ route('admin.crm_customers.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($crm_customers) > 0 ? 'datatable' : '' }} @can('crm_customer_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('crm_customer_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.crm-customers.fields.first-name')</th>
                        <th>@lang('quickadmin.crm-customers.fields.last-name')</th>
                        <th>@lang('quickadmin.crm-customers.fields.crm-status')</th>
                        <th>@lang('quickadmin.crm-customers.fields.email')</th>
                        <th>@lang('quickadmin.crm-customers.fields.phone')</th>
                        <th>@lang('quickadmin.crm-customers.fields.address')</th>
                        <th>@lang('quickadmin.crm-customers.fields.skype')</th>
                        <th>@lang('quickadmin.crm-customers.fields.website')</th>
                        <th>@lang('quickadmin.crm-customers.fields.description')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($crm_customers) > 0)
                        @foreach ($crm_customers as $crm_customer)
                            <tr data-entry-id="{{ $crm_customer->id }}">
                                @can('crm_customer_delete')
                                    <td></td>
                                @endcan

                                <td field-key='first_name'>{{ $crm_customer->first_name }}</td>
                                <td field-key='last_name'>{{ $crm_customer->last_name }}</td>
                                <td field-key='crm_status'>{{ $crm_customer->crm_status->title ?? '' }}</td>
                                <td field-key='email'>{{ $crm_customer->email }}</td>
                                <td field-key='phone'>{{ $crm_customer->phone }}</td>
                                <td field-key='address'>{{ $crm_customer->address }}</td>
                                <td field-key='skype'>{{ $crm_customer->skype }}</td>
                                <td field-key='website'>{{ $crm_customer->website }}</td>
                                <td field-key='description'>{!! $crm_customer->description !!}</td>
                                                                <td>
                                    @can('crm_customer_view')
                                    <a href="{{ route('admin.crm_customers.show',[$crm_customer->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('crm_customer_edit')
                                    <a href="{{ route('admin.crm_customers.edit',[$crm_customer->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('crm_customer_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.crm_customers.destroy', $crm_customer->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="14">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('crm_customer_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.crm_customers.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/crm_customers/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-customers.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.first-name')</th>
                            <td field-key='first_name'>{{ $crm_customer->first_name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.last-name')</th>
                            <td field-key='last_name'>{{ $crm_customer->last_name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.crm-status')</th>
                            <td field-key='crm_status'>{{ $crm_customer->crm_status->title ?? '' }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.email')</th>
                            <td field-key='email'>{{ $crm_customer->email }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.phone')</th>
                            <td field-key='phone'>{{ $crm_customer->phone }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.address')</th>
                            <td field-key='address'>{{ $crm_customer->address }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.skype')</th>
                            <td field-key='skype'>{{ $crm_customer->skype }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.website')</th>
                            <td field-key='website'>{{ $crm_customer->website }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.crm-customers.fields.description')</th>
                            <td field-key='description'>{!! $crm_customer->description !!}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#crm_notes" aria-controls="crm_notes" role="tab" data-toggle="tab">Notes</a></li>
<li role="presentation" class=""><a href="#crm_documents" aria-controls="crm_documents" role="tab" data-toggle="tab">Documents</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="crm_notes">
<table class="table table-bordered table-striped {{ count($crm_notes) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.crm-notes.fields.customer')</th>
                        <th>@lang('quickadmin.crm-notes.fields.note')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($crm_notes) > 0)
            @foreach ($crm_notes as $crm_note)
                <tr data-entry-id="{{ $crm_note->id }}">
                    <td field-key='customer'>{{ $crm_note->customer->first_name ?? '' }}</td>
                                <td field-key='note'>{!! $crm_note->note !!}</td>
                                                                <td>
                                    @can('crm_note_view')
                                    <a href="{{ route('admin.crm_notes.show',[$crm_note->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('crm_note_edit')
                                    <a href="{{ route('admin.crm_notes.edit',[$crm_note->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('crm_note_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.crm_notes.destroy', $crm_note->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="7">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="crm_documents">
<table class="table table-bordered table-striped {{ count($crm_documents) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.crm-documents.fields.customer')</th>
                        <th>@lang('quickadmin.crm-documents.fields.name')</th>
                        <th>@lang('quickadmin.crm-documents.fields.description')</th>
                        <th>@lang('quickadmin.crm-documents.fields.file')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($crm_documents) > 0)
            @foreach ($crm_documents as $crm_document)
                <tr data-entry-id="{{ $crm_document->id }}">
                    <td field-key='customer'>{{ $crm_document->customer->first_name ?? '' }}</td>
                                <td field-key='name'>{{ $crm_document->name }}</td>
                                <td field-key='description'>{!! $crm_document->description !!}</td>
                                <td field-key='file'>@if($crm_document->file)<a href="{{ asset(env('UPLOAD_PATH').'/' . $crm_document->file) }}" target="_blank">Download file</a>@endif</td>
                                                                <td>
                                    @can('crm_document_view')
                                    <a href="{{ route('admin.crm_documents.show',[$crm_document->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('crm_document_edit')
                                    <a href="{{ route('admin.crm_documents.edit',[$crm_document->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('crm_document_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.crm_documents.destroy', $crm_document->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.crm_customers.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop