routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('crm_statuses', 'Admin\CrmStatusesController');
    Route::post('crm_statuses_mass_destroy', ['uses' => 'Admin\CrmStatusesController@massDestroy', 'as' => 'crm_statuses.mass_destroy']);
    Route::resource('crm_customers', 'Admin\CrmCustomersController');
    Route::post('crm_customers_mass_destroy', ['uses' => 'Admin\CrmCustomersController@massDestroy', 'as' => 'crm_customers.mass_destroy']);
    Route::resource('crm_notes', 'Admin\CrmNotesController');
    Route::post('crm_notes_mass_destroy', ['uses' => 'Admin\CrmNotesController@massDestroy', 'as' => 'crm_notes.mass_destroy']);
    Route::resource('crm_documents', 'Admin\CrmDocumentsController');
    Route::post('crm_documents_mass_destroy', ['uses' => 'Admin\CrmDocumentsController@massDestroy', 'as' => 'crm_documents.mass_destroy']);
    Route::resource('inbounds', 'Admin\InboundsController');
    Route::post('inbounds_mass_destroy', ['uses' => 'Admin\InboundsController@massDestroy', 'as' => 'inbounds.mass_destroy']);
    Route::post('inbounds_restore/{id}', ['uses' => 'Admin\InboundsController@restore', 'as' => 'inbounds.restore']);
    Route::delete('inbounds_perma_del/{id}', ['uses' => 'Admin\InboundsController@perma_del', 'as' => 'inbounds.perma_del']);
    Route::resource('bookings', 'Admin\BookingsController');
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingsController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::post('bookings_restore/{id}', ['uses' => 'Admin\BookingsController@restore', 'as' => 'bookings.restore']);
    Route::delete('bookings_perma_del/{id}', ['uses' => 'Admin\BookingsController@perma_del', 'as' => 'bookings.perma_del']);
    Route::get('booking_details','Admin\BookingDetailsController@index');

    Route::resource('booking_details', 'Admin\BookingDetailsController');
    Route::post('booking_details_mass_destroy', ['uses' => 'Admin\BookingDetailsController@massDestroy', 'as' => 'booking_details.mass_destroy']);
    Route::post('booking_details_restore/{id}', ['uses' => 'Admin\BookingDetailsController@restore', 'as' => 'booking_details.restore']);
    Route::delete('booking_details_perma_del/{id}', ['uses' => 'Admin\BookingDetailsController@perma_del', 'as' => 'booking_details.perma_del']);



 
});

app/Http/Controllers/Admin/CrmStatusesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CrmStatus;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCrmStatusesRequest;
use App\Http\Requests\Admin\UpdateCrmStatusesRequest;

class CrmStatusesController extends Controller
{
    /**
     * Display a listing of CrmStatus.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('crm_status_access')) {
            return abort(401);
        }


                $crm_statuses = CrmStatus::all();

        return view('admin.crm_statuses.index', compact('crm_statuses'));
    }

    /**
     * Show the form for creating new CrmStatus.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('crm_status_create')) {
            return abort(401);
        }
        return view('admin.crm_statuses.create');
    }

    /**
     * Store a newly created CrmStatus in storage.
     *
     * @param  \App\Http\Requests\StoreCrmStatusesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCrmStatusesRequest $request)
    {
        if (! Gate::allows('crm_status_create')) {
            return abort(401);
        }
        $crm_status = CrmStatus::create($request->all());



        return redirect()->route('admin.crm_statuses.index');
    }


    /**
     * Show the form for editing CrmStatus.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('crm_status_edit')) {
            return abort(401);
        }
        $crm_status = CrmStatus::findOrFail($id);

        return view('admin.crm_statuses.edit', compact('crm_status'));
    }

    /**
     * Update CrmStatus in storage.
     *
     * @param  \App\Http\Requests\UpdateCrmStatusesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCrmStatusesRequest $request, $id)
    {
        if (! Gate::allows('crm_status_edit')) {
            return abort(401);
        }
        $crm_status = CrmStatus::findOrFail($id);
        $crm_status->update($request->all());



        return redirect()->route('admin.crm_statuses.index');
    }


    /**
     * Display CrmStatus.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('crm_status_view')) {
            return abort(401);
        }
        $crm_customers = \App\CrmCustomer::where('crm_status_id', $id)->get();

        $crm_status = CrmStatus::findOrFail($id);

        return view('admin.crm_statuses.show', compact('crm_status', 'crm_customers'));
    }


    /**
     * Remove CrmStatus from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('crm_status_delete')) {
            return abort(401);
        }
        $crm_status = CrmStatus::findOrFail($id);
        $crm_status->delete();

        return redirect()->route('admin.crm_statuses.index');
    }

    /**
     * Delete all selected CrmStatus at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('crm_status_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = CrmStatus::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/crm_statuses/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-statuses.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.crm_statuses.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('title', trans('quickadmin.crm-statuses.fields.title').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/crm_statuses/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-statuses.title')</h3>
    
    {!! Form::model($crm_status, ['method' => 'PUT', 'route' => ['admin.crm_statuses.update', $crm_status->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('title', trans('quickadmin.crm-statuses.fields.title').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/crm_statuses/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-statuses.title')</h3>
    @can('crm_status_create')
    <p>
        <a href="{{ route('admin.crm_statuses.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($crm_statuses) > 0 ? 'datatable' : '' }} @can('crm_status_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('crm_status_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.crm-statuses.fields.title')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($crm_statuses) > 0)
                        @foreach ($crm_statuses as $crm_status)
                            <tr data-entry-id="{{ $crm_status->id }}">
                                @can('crm_status_delete')
                                    <td></td>
                                @endcan

                                <td field-key='title'>{{ $crm_status->title }}</td>
                                                                <td>
                                    @can('crm_status_view')
                                    <a href="{{ route('admin.crm_statuses.show',[$crm_status->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('crm_status_edit')
                                    <a href="{{ route('admin.crm_statuses.edit',[$crm_status->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('crm_status_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.crm_statuses.destroy', $crm_status->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('crm_status_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.crm_statuses.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/crm_statuses/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.crm-statuses.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.crm-statuses.fields.title')</th>
                            <td field-key='title'>{{ $crm_status->title }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#crm_customers" aria-controls="crm_customers" role="tab" data-toggle="tab">Customers</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="crm_customers">
<table class="table table-bordered table-striped {{ count($crm_customers) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.crm-customers.fields.first-name')</th>
                        <th>@lang('quickadmin.crm-customers.fields.last-name')</th>
                        <th>@lang('quickadmin.crm-customers.fields.crm-status')</th>
                        <th>@lang('quickadmin.crm-customers.fields.email')</th>
                        <th>@lang('quickadmin.crm-customers.fields.phone')</th>
                        <th>@lang('quickadmin.crm-customers.fields.address')</th>
                        <th>@lang('quickadmin.crm-customers.fields.skype')</th>
                        <th>@lang('quickadmin.crm-customers.fields.website')</th>
                        <th>@lang('quickadmin.crm-customers.fields.description')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($crm_customers) > 0)
            @foreach ($crm_customers as $crm_customer)
                <tr data-entry-id="{{ $crm_customer->id }}">
                    <td field-key='first_name'>{{ $crm_customer->first_name }}</td>
                                <td field-key='last_name'>{{ $crm_customer->last_name }}</td>
                                <td field-key='crm_status'>{{ $crm_customer->crm_status->title ?? '' }}</td>
                                <td field-key='email'>{{ $crm_customer->email }}</td>
                                <td field-key='phone'>{{ $crm_customer->phone }}</td>
                                <td field-key='address'>{{ $crm_customer->address }}</td>
                                <td field-key='skype'>{{ $crm_customer->skype }}</td>
                                <td field-key='website'>{{ $crm_customer->website }}</td>
                                <td field-key='description'>{!! $crm_customer->description !!}</td>
                                                                <td>
                                    @can('crm_customer_view')
                                    <a href="{{ route('admin.crm_customers.show',[$crm_customer->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('crm_customer_edit')
                                    <a href="{{ route('admin.crm_customers.edit',[$crm_customer->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('crm_customer_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.crm_customers.destroy', $crm_customer->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="14">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.crm_statuses.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop